theme: minimal-mistakes-jekyll
title: 내 프로필 페이지
description: 안녕하세요. Jekyll로 만든 제 웹사이트입니다.
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Site Settings
title: "Min-Sik Kim"
description: "PostDoc in Earth and Planetary Science"
url: "https://yukms.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
